title: retraining-model
hero_image: images/banner.png
description: retraining-model description
version: 4
listed: false
copyedit: false
last_tested: "2020-06-16"
steps:
  - title: Introduction
  - title: Get and split training data
  - title: Prepare the model for retraining
  - title: Add your new layers
  - title: Retrain the model
  - title: Test your model
  - title: What's next?